<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dateTime = Carbon::now()->format('Y-m-d H:i:s'); 
        DB::table('users')->insert([
            //Lãnh Đạo
            ['id'=>1,
            'position_id'=>1,
            'department_id'=>5,
            'account_id'=>1,
            'name'=>'Nguyễn Văn Nầy',
            'date_of_birth'=>'1974-01-01',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0913730558',
            'email'=>'nvnay@travinh.gov.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>2,
            'position_id'=>2,
            'department_id'=>5,
            'account_id'=>2,
            'name'=>'Nguyễn Thanh Luân',
            'date_of_birth'=>'1974-01-01',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0913659289',
            'email'=>'ntluan@travinh.gov.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            
            ['id'=>3,
            'position_id'=>2,
            'department_id'=>5,
            'account_id'=>4,
            'name'=>'Nguyễn Văn Chuẩn',
            'date_of_birth'=>'1974-01-01',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0916112003',
            'email'=>'nvchuan@travinh.gov.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
             ['id'=>4,
            'position_id'=>2,
            'department_id'=>5,
            'account_id'=>5,
            'name'=>'Bùi Thống Nhứt',
            'date_of_birth'=>'1974-01-01',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0945464499',
            'email'=>'btnhut@travinh.gov.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            //Quản Trị Hệ Thống
            ['id'=>5,
            'position_id'=>3,
            'department_id'=>2,
            'account_id'=>6,
            'name'=>'Huỳnh Khắc Sử',
            'date_of_birth'=>'2000-12-10',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0392096959',
            'email'=>'sub1809508@student.ctu.edu.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>6,
            'position_id'=>4,
            'department_id'=>2,
            'account_id'=>7,
            'name'=>'Nguyễn Quỳnh Vy Vy',
            'date_of_birth'=>'2001-08-23',
            'sex'=>'1',
            'address'=>'Bạc Liêu',
            'phone'=>'0392096958',
            'email'=>'vyb1909308@student.ctu.edu.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            //Bộ Phận Quản Lý
            ['id'=>7,
            'position_id'=>4,
            'department_id'=>6,
            'account_id'=>8,
            'name'=>'Nguyễn Khánh Linh',
            'date_of_birth'=>'2000-09-10',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0392096958',
            'email'=>'linhnguyen@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>8,
            'position_id'=>5,
            'department_id'=>6,
            'account_id'=>9,
            'name'=>'Lâm Thanh Khang',
            'date_of_birth'=>'2000-10-10',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0392096957',
            'email'=>'ltkhang@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            //Bộ Phận Quản Lý
            ['id'=>9,
            'position_id'=>3,
            'department_id'=>7,
            'account_id'=>10,
            'name'=>'Nguyễn Trung Hậu',
            'date_of_birth'=>'2000-12-22',
            'sex'=>'0',
            'address'=>'Vĩnh Long',
            'phone'=>'0392096956',
            'email'=>'haub1809456@student.ctu.edu.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>10,
            'position_id'=>4,
            'department_id'=>7,
            'account_id'=>11,
            'name'=>'Trần Nguyễn Hữu Dinh',
            'date_of_birth'=>'2000-10-22',
            'sex'=>'0',
            'address'=>'Vĩnh Long',
            'phone'=>'0392096955',
            'email'=>'dinhb1809442@student.ctu.edu.vn',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>11,
            'position_id'=>5,
            'department_id'=>7,
            'account_id'=>12,
            'name'=>'Nguyễn Hữu Đa',
            'date_of_birth'=>'1990-10-12',
            'sex'=>'0',
            'address'=>'Yên Bái',
            'phone'=>'0392096954',
            'email'=>'nhda@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>12,
            'position_id'=>5,
            'department_id'=>7,
            'account_id'=>13,
            'name'=>'Huỳnh Thị Thảo Nghi',
            'date_of_birth'=>'1995-10-12',
            'sex'=>'1',
            'address'=>'Trà Vinh',
            'phone'=>'0392096953',
            'email'=>'httnghi@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>13,
            'position_id'=>5,
            'department_id'=>7,
            'account_id'=>13,
            'name'=>'Lâm Văn Hùng',
            'date_of_birth'=>'1995-09-12',
            'sex'=>'1',
            'address'=>'Trà Vinh',
            'phone'=>'0392096950',
            'email'=>'lvhung@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>14,
            'position_id'=>5,
            'department_id'=>7,
            'account_id'=>14,
            'name'=>'Lê Hữu Nghĩa',
            'date_of_birth'=>'1996-10-12',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0392096952',
            'email'=>'lhnghia@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],
            ['id'=>15,
            'position_id'=>5,
            'department_id'=>7,
            'account_id'=>15,
            'name'=>'Lê Hữu Nghị',
            'date_of_birth'=>'1998-10-12',
            'sex'=>'0',
            'address'=>'Trà Vinh',
            'phone'=>'0392096951',
            'email'=>'lhnghi@gmail.com',
            'created_at' => $dateTime,
            'updated_at' => $dateTime,
            ],


        ]);
    }
}
